In [2]:
import numpy as np
import cv2

In [3]:
one = cv2.imread("KakaoTalk_20220328_134200684.jpg")
four = cv2.imread("KakaoTalk_20220328_134200807.jpg")

In [3]:
print(type(one))
print(type(four))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
print(one.shape)
print(four.shape)

(1152, 1152, 3)
(1152, 1152, 3)


In [5]:
one_T = one.T

In [11]:
cv2.imshow("transfer_one", one_T)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:124: error: (-215:Assertion failed) bmi && width >= 0 && height >= 0 && (bpp == 8 || bpp == 24 || bpp == 32) in function 'FillBitmapInfo'


In [10]:
print(one_T)

[[[144 145 147 ... 135 176 216]
  [143 144 146 ... 135 176 216]
  [142 143 145 ... 134 176 216]
  ...
  [139 139 139 ... 132 172 213]
  [177 177 177 ... 172 198 226]
  [216 216 216 ... 214 226 239]]

 [[145 146 148 ... 138 177 216]
  [144 145 147 ... 138 177 216]
  [143 144 146 ... 137 177 216]
  ...
  [140 140 140 ... 133 172 213]
  [178 178 178 ... 173 198 226]
  [217 217 217 ... 215 226 239]]

 [[141 142 144 ... 136 175 216]
  [140 141 143 ... 136 175 216]
  [139 140 142 ... 135 175 216]
  ...
  [138 138 138 ... 131 172 213]
  [176 176 176 ... 171 198 226]
  [215 215 215 ... 213 226 239]]]


In [5]:
# 합성은 됐는데 음영이 이상하다..
sum = one + four
# one_30 = one * 2
# four_30 = four * 2
# sum = one_30 + four_30
print(sum)

[[[ 21  25  19]
  [ 20  24  18]
  [ 22  26  20]
  ...
  [ 20  25  18]
  [ 96 100  96]
  [173 177 173]]

 [[ 24  28  22]
  [ 23  27  21]
  [ 25  29  23]
  ...
  [ 21  26  19]
  [ 96 100  96]
  [172 176 172]]

 [[ 28  32  26]
  [ 27  31  25]
  [ 27  31  25]
  ...
  [ 22  27  20]
  [ 97 101  97]
  [174 178 174]]

 ...

 [[ 12  16  12]
  [ 12  16  12]
  [ 11  15  11]
  ...
  [ 11  12  10]
  [ 91  92  90]
  [172 173 171]]

 [[ 94  96  92]
  [ 94  96  92]
  [ 93  95  91]
  ...
  [ 89  92  90]
  [141 144 142]
  [196 199 197]]

 [[174 174 174]
  [174 174 174]
  [174 175 173]
  ...
  [169 172 170]
  [196 199 197]
  [222 225 223]]]


In [6]:
t = sum * 3
cv2.imshow('t', t)
# cv2.imshow('sum', sum)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
# 밝기조절(밝아지는 것 같긴 하다.)
bright_1 = one + 20
bright_2 = four + 40

In [8]:
cv2.imshow('bright_1', bright_1)
cv2.imshow('bright_2', bright_2)

cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(a[0][1])

2


In [21]:
for i in range(len(a)):
    print(a[i])

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
for j in range(len(one)):
    print(one[j])

[[144 145 141]
 [143 144 140]
 [142 143 139]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[145 146 142]
 [144 145 141]
 [143 144 140]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[147 148 144]
 [146 147 143]
 [145 146 142]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[148 149 145]
 [147 148 144]
 [146 147 143]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[148 149 145]
 [147 148 144]
 [146 147 143]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[147 148 144]
 [146 147 143]
 [146 147 143]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[147 148 144]
 [146 147 143]
 [146 147 143]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[146 147 143]
 [146 147 143]
 [146 147 143]
 ...
 [139 140 138]
 [177 178 176]
 [216 217 215]]
[[144 146 140]
 [144 146 140]
 [144 146 140]
 ...
 [140 141 139]
 [178 179 177]
 [216 217 215]]
[[145 146 144]
 [145 146 144]
 [145 146 142]
 ...
 [140 141 139]
 [177 178 176]
 [215 216 214]]
[[145 146 144]
 [145 146 144]
 [145 146 

In [5]:
def rotate_matrix_90(a):
    N = len(a)
    res = [[0] * N for _ in range(N)]

    for row in range(N):
        for col in range(N):
            res[col][N-1-row] = a[row][col]
    return res

In [8]:
print(rotate_matrix_90(a))

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [4]:
gray_image = cv2.cvtColor(one, cv2.COLOR_BGR2GRAY)
gray_image.shape

(1152, 1152)

In [8]:
for k in range(len(gray_image)):
    print(gray_image[k])

[144 143 142 ... 139 177 216]
[145 144 143 ... 139 177 216]
[147 146 145 ... 139 177 216]
[148 147 146 ... 139 177 216]
[148 147 146 ... 139 177 216]
[147 146 146 ... 139 177 216]
[147 146 146 ... 139 177 216]
[146 146 146 ... 139 177 216]
[144 144 144 ... 140 178 216]
[145 145 145 ... 140 177 215]
[145 145 145 ... 141 178 216]
[145 145 146 ... 142 179 217]
[145 146 146 ... 142 178 216]
[146 146 147 ... 143 180 217]
[147 147 148 ... 144 180 217]
[148 148 148 ... 144 180 217]
[147 147 147 ... 144 181 217]
[148 148 147 ... 145 181 218]
[149 148 148 ... 145 181 218]
[149 149 148 ... 145 181 218]
[150 150 149 ... 145 181 217]
[151 150 149 ... 145 180 216]
[150 150 149 ... 145 180 216]
[149 149 148 ... 145 180 217]
[146 146 147 ... 144 181 218]
[146 146 147 ... 144 180 217]
[145 145 146 ... 144 180 217]
[145 145 145 ... 144 180 217]
[146 146 146 ... 145 180 217]
[146 146 146 ... 146 181 218]
[146 147 146 ... 146 182 219]
[147 148 147 ... 146 181 218]
[146 147 147 ... 146 182 218]
[148 148 1

In [9]:
def rotate_matrix_90(gray_image):
    N = len(gray_image)
    res = [[0] * N for _ in range(N)]

    for row in range(N):
        for col in range(N):
            res[col][N-1-row] = gray_image[row][col]
    return res

In [13]:
print(np.array(rotate_matrix_90(gray_image)))

[[216 176 137 ... 147 145 144]
 [216 176 137 ... 146 144 143]
 [216 176 136 ... 145 143 142]
 ...
 [213 172 132 ... 139 139 139]
 [226 198 172 ... 177 177 177]
 [239 226 214 ... 216 216 216]]


In [14]:
one_90 = np.array(rotate_matrix_90(gray_image))

cv2.imshow('90', one_90)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
def rotate_matrix_90(one):
    N = len(one)
    res = [[0] * N for _ in range(N)]

    for c in range(3):
        for row in range(N):
            for col in range(N):
                res[col][N-1-row] = one[row][col]
        return res

In [16]:
cone_90 = np.array(rotate_matrix_90(one))

print(cone_90)

[[[216 216 216]
  [176 177 175]
  [135 138 136]
  ...
  [147 148 144]
  [145 146 142]
  [144 145 141]]

 [[216 216 216]
  [176 177 175]
  [135 138 136]
  ...
  [146 147 143]
  [144 145 141]
  [143 144 140]]

 [[216 216 216]
  [176 177 175]
  [134 137 135]
  ...
  [145 146 142]
  [143 144 140]
  [142 143 139]]

 ...

 [[213 213 213]
  [172 172 172]
  [132 133 131]
  ...
  [139 140 138]
  [139 140 138]
  [139 140 138]]

 [[226 226 226]
  [198 198 198]
  [172 173 171]
  ...
  [177 178 176]
  [177 178 176]
  [177 178 176]]

 [[239 239 239]
  [226 226 226]
  [214 215 213]
  ...
  [216 217 215]
  [216 217 215]
  [216 217 215]]]


In [25]:
cv2.imshow('color', cone_90)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
def rotate_matrix_180(one):
    N = len(one)
    res = [[0] * N for _ in range(N)]    # 변형할 행렬

    for c in range(3):
        for row in range(N):
            for col in range(N):
                res[N - 1 - row][N - 1 - col] = one[row][col]
    return res

In [19]:
cone_180 = np.array(rotate_matrix_180(one))
print(cone_180)

[[[239 239 239]
  [226 226 226]
  [213 213 213]
  ...
  [216 216 216]
  [216 216 216]
  [216 216 216]]

 [[226 226 226]
  [198 198 198]
  [172 172 172]
  ...
  [176 177 175]
  [176 177 175]
  [176 177 175]]

 [[214 215 213]
  [172 173 171]
  [132 133 131]
  ...
  [134 137 135]
  [135 138 136]
  [135 138 136]]

 ...

 [[216 217 215]
  [177 178 176]
  [139 140 138]
  ...
  [145 146 142]
  [146 147 143]
  [147 148 144]]

 [[216 217 215]
  [177 178 176]
  [139 140 138]
  ...
  [143 144 140]
  [144 145 141]
  [145 146 142]]

 [[216 217 215]
  [177 178 176]
  [139 140 138]
  ...
  [142 143 139]
  [143 144 140]
  [144 145 141]]]


In [20]:
cv2.imshow('180', cone_180)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
def rotate_matrix_270(one):
    N = len(one)
    res = [[0] * N for _ in range(N)]   # 변형할 행렬

    for c in range(3):
        for row in range(N):
            for col in range(N):
                res[N - 1 - col][row] = one[row][col]
    return res

In [23]:
cone_270 = np.array(rotate_matrix_270(one))
print(cone_270)

[[[216 217 215]
  [216 217 215]
  [216 217 215]
  ...
  [214 215 213]
  [226 226 226]
  [239 239 239]]

 [[177 178 176]
  [177 178 176]
  [177 178 176]
  ...
  [172 173 171]
  [198 198 198]
  [226 226 226]]

 [[139 140 138]
  [139 140 138]
  [139 140 138]
  ...
  [132 133 131]
  [172 172 172]
  [213 213 213]]

 ...

 [[142 143 139]
  [143 144 140]
  [145 146 142]
  ...
  [134 137 135]
  [176 177 175]
  [216 216 216]]

 [[143 144 140]
  [144 145 141]
  [146 147 143]
  ...
  [135 138 136]
  [176 177 175]
  [216 216 216]]

 [[144 145 141]
  [145 146 142]
  [147 148 144]
  ...
  [135 138 136]
  [176 177 175]
  [216 216 216]]]


In [24]:
cv2.imshow('270', cone_270)
cv2.waitKey()
cv2.destroyAllWindows()

In [26]:
def rotate_matrix_90(four):
    N = len(four)
    res = [[0] * N for _ in range(N)]

    for c in range(3):
        for row in range(N):
            for col in range(N):
                res[col][N-1-row] = four[row][col]
        return res

In [27]:
cfour_90 = np.array(rotate_matrix_90(four))
print(cfour_90)

[[[214 214 214]
  [174 175 173]
  [133 134 132]
  ...
  [137 140 138]
  [135 138 136]
  [133 136 134]]

 [[214 214 214]
  [174 175 173]
  [133 134 132]
  ...
  [137 140 138]
  [135 138 136]
  [133 136 134]]

 [[214 215 213]
  [173 174 172]
  [133 134 132]
  ...
  [138 141 139]
  [138 141 139]
  [136 139 137]]

 ...

 [[212 215 213]
  [173 176 174]
  [135 135 135]
  ...
  [139 143 138]
  [138 142 137]
  [137 141 136]]

 [[226 229 227]
  [199 202 200]
  [175 175 175]
  ...
  [176 179 177]
  [175 178 176]
  [175 178 176]]

 [[239 242 240]
  [226 229 227]
  [214 214 214]
  ...
  [214 217 215]
  [212 215 213]
  [213 216 214]]]


In [28]:
cv2.imshow('four 90', cfour_90)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
def rotate_matrix_180(four):
    N = len(four)
    res = [[0] * N for _ in range(N)]

    for c in range(3):
        for row in range(N):
            for col in range(N):
                res[N - 1 - row][N - 1 - col] = four[row][col]
    return res

In [30]:
cfour_180 = np.array(rotate_matrix_180(four))
print(cfour_180)

[[[239 242 240]
  [226 229 227]
  [212 215 213]
  ...
  [214 215 213]
  [214 214 214]
  [214 214 214]]

 [[226 229 227]
  [199 202 200]
  [173 176 174]
  ...
  [173 174 172]
  [174 175 173]
  [174 175 173]]

 [[214 214 214]
  [175 175 175]
  [135 135 135]
  ...
  [133 134 132]
  [133 134 132]
  [133 134 132]]

 ...

 [[214 217 215]
  [176 179 177]
  [139 143 138]
  ...
  [138 141 139]
  [137 140 138]
  [137 140 138]]

 [[212 215 213]
  [175 178 176]
  [138 142 137]
  ...
  [138 141 139]
  [135 138 136]
  [135 138 136]]

 [[213 216 214]
  [175 178 176]
  [137 141 136]
  ...
  [136 139 137]
  [133 136 134]
  [133 136 134]]]


In [32]:
cv2.imshow('four 180', cfour_180)
cv2.waitKey()
cv2.destroyAllWindows()